### ISSUE TITLE
As a social media user, I can select a person and see the social media platforms they are using 

### ISSUE THREAD

**Issue by KevinChuangCH** [CS2103JAN2018-F12-B3/main#13]
so that I do not have to go to various platform to check.

**Comment by KevinChuangCH** [comment]
Implementing tabs UI.

**Comment by Nethergale** [comment]
I'm also assigning this user story to myself considering that I am working on a section of this story, particularly the "see the social media platforms they are using". All the platforms that are added to a person will be shown on his/her person card.

**Comment by KevinChuangCH** [comment]
I have just merged the UI with tabs and all. Now they are still loading the dummy search page, but you can just replace the dummy search page URL with the profile URL. I think that will do the job.
