### ISSUE TITLE
Update the README page: add a UI mockup

### ISSUE THREAD

**Issue by shadow2496** [CS2103JAN2018-F12-B3/main#61]
... of our intended final product.
Note that the image of the UI should be `docs/images/Ui.png`.

**Comment by KevinChuangCH** [comment]
See https://github.com/CS2103JAN2018-F12-B3/main/pull/76

**Comment by KevinChuangCH** [comment]
PR merged: https://github.com/CS2103JAN2018-F12-B3/main/pull/76
