### ISSUE TITLE
[Individual] Contributed code to v1.4

### ISSUE THREAD

**Issue by Nethergale** [CS2103JAN2018-F12-B3/main#94]

**Comment by KevinChuangCH** [comment]
https://github.com/CS2103JAN2018-F12-B3/main/pull/97/

**Comment by KevinChuangCH** [comment]
https://github.com/CS2103JAN2018-F12-B3/main/pull/90

**Comment by KevinChuangCH** [comment]
https://github.com/CS2103JAN2018-F12-B3/main/pull/100
